### ISSUE TITLE
查询记录 生成execl

### ISSUE THREAD

**Issue by kindson07** [cntvc/star-rail-tools#37]
### 系统版本 (System Version)

Windows10 or Windows11

### 软件版本 (Software version)

2.2.0

### 发生了什么？预计会发生什么 (What happened? what did you expect to happen?)

![螢幕擷取畫面 2023-12-11 221849](https://github.com/cntvc/star-rail-tools/assets/109346442/fe513265-816c-4f77-a162-116b421d8d7a)

**Comment by cntvc** [comment]
请上传日志，并附操作步骤，只看截图无法定位bug。

**Comment by kindson07** [comment]
2023-12-13 21:49:57 | DEBUG | client.py:318 | export_to_execl | message: Export gacha record to Execl.
2023-12-13 21:49:58 | DEBUG | handler.py:22 | wrapper | message: Traceback (most recent call last):
  File "star_rail\tui\handler.py", line 12, in wrapper
  File "star_rail\tui\handler.py", line 36, in wrapper
  File "star_rail\tui\widgets\_record.py", line 122, in export_to_execl
  File "star_rail\module\record\client.py", line 385, in export_to_execl
ValueError: invalid literal for int() with base 10: ''

**Comment by kindson07** [comment]
[sql_2023_12.log](https://github.com/cntvc/star-rail-tools/files/13661425/sql_2023_12.log)

生成SRGF 是可以的 但excel 就fail

**Comment by kindson07** [comment]
[log_2023_12.log](https://github.com/cntvc/star-rail-tools/files/13661445/log_2023_12.log)
就是按生成EXCEL 然后彈出error
生成SRGF 是可以的 但excel 就error

**Comment by cntvc** [comment]
可以试下新版： https://github.com/cntvc/star-rail-tools/releases/tag/2.2.1

导出Execl时必须要`rank_type`字段，没有的话就只能显示默认颜色了，不会对单元格进行着色区分。
