### ISSUE TITLE
导出抽卡记录时发生错误

### ISSUE THREAD

**Issue by xulingran** [cntvc/star-rail-tools#8]
### 系统版本 (System Version)

Windows10 or Windows11

### 软件版本 (Software version)

1.0.0

### 发生了什么？预计会发生什么 (What happened? what did you expect to happen?)

获取限定跃迁时发生错误
[log_2023_05.log](https://github.com/cntvc/star-rail-tools/files/11561754/log_2023_05.log)

### 相关日志输出文本 (Relevant log output)

```Text
2023-05-25 14:30:26 | ERROR | main.py:138 | <module>()  | message: An error has been caught in function '<module>', process 'MainProcess' (18900), thread 'MainThread' (7824):
Traceback (most recent call last):

> File "star_rail\main.py", line 138, in <module>

  File "star_rail\main.py", line 134, in run

  File "star_rail\utils\menu.py", line 84, in run

  File "star_rail\utils\menu.py", line 86, in run

  File "star_rail\module\gacha\__init__.py", line 48, in export_by_webcache

  File "star_rail\module\gacha\__init__.py", line 89, in save_and_show_result

  File "star_rail\module\gacha\gacha_log.py", line 138, in analyze

IndexError: list index out of range
```

**Comment by cntvc** [comment]
感谢反馈，已在 1.0.1 版本修复
